/* ============================================================
   First-time setup helper.

     npm run setup                 → asks you a few questions
     npm run setup -- --defaults   → uses localhost/root/no password
     npm run setup -- --host=… --user=… --password=… --db=…

   Writes your .env file, then checks it can actually reach MySQL
   and creates the database if it doesn't exist yet.
   ============================================================ */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ENV_PATH = path.join(__dirname, '.env');
const line = () => console.log('='.repeat(62));

// ── Core logic (no prompting — kept separate so it's easy to test) ──
function writeEnv(cfg) {
  const env = `# Generated by "npm run setup" — you can edit this by hand any time.

DB_HOST=${cfg.host}
DB_PORT=${cfg.port}
DB_USER=${cfg.user}
DB_PASSWORD=${cfg.password}
DB_NAME=${cfg.dbName}

# Set to true only when connecting to a cloud MySQL provider.
DB_SSL=false

# Signs login tokens. Randomly generated — keep it secret.
JWT_SECRET=${crypto.randomBytes(48).toString('hex')}

PORT=4000
`;
  fs.writeFileSync(ENV_PATH, env);
}

async function verifyConnection(cfg) {
  const mysql = require('mysql2/promise');
  const conn = await mysql.createConnection({
    host: cfg.host,
    port: Number(cfg.port),
    user: cfg.user,
    password: cfg.password,
    connectTimeout: 10000
  });
  await conn.query(
    `CREATE DATABASE IF NOT EXISTS \`${cfg.dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`
  );
  await conn.end();
}

function reportSuccess() {
  console.log('');
  line();
  console.log('  SUCCESS — connected to MySQL, database is ready.');
  line();
  console.log('');
  console.log('  Next step:   npm start');
  console.log('  Then open:   http://localhost:4000');
  console.log('');
}

function reportFailure(err, cfg) {
  console.log('');
  line();
  console.log('  COULD NOT CONNECT TO MYSQL');
  line();
  console.log('');
  if (err.code === 'ECONNREFUSED' || err.code === 'ETIMEDOUT') {
    console.log(`  Nothing is listening at ${cfg.host}:${cfg.port}.`);
    console.log('  Your MySQL server is probably not running.');
    console.log('');
    console.log('  If you installed XAMPP: open the XAMPP Control Panel');
    console.log('  and click "Start" next to MySQL, then run setup again.');
  } else if (err.code === 'ER_ACCESS_DENIED_ERROR') {
    console.log(`  MySQL rejected the username/password for "${cfg.user}".`);
    console.log('');
    console.log('  With XAMPP the default is username "root" with an');
    console.log('  empty password. Run setup again to retry.');
  } else if (err.code === 'ENOTFOUND') {
    console.log(`  The host "${cfg.host}" could not be found.`);
  } else {
    console.log(`  ${err.message}`);
    console.log(`  (code: ${err.code || 'unknown'})`);
  }
  console.log('');
  console.log('  Your .env was still saved — fix MySQL, then run:');
  console.log('    npm start');
  console.log('');
}

async function run(cfg) {
  writeEnv(cfg);
  console.log('');
  console.log('  Created .env  [ok]');
  console.log('');
  console.log('  Checking the connection to MySQL...');
  try {
    await verifyConnection(cfg);
    reportSuccess();
    return 0;
  } catch (err) {
    reportFailure(err, cfg);
    return 1;
  }
}

// ── Argument parsing ────────────────────────────────────────
function parseArgs(argv) {
  const out = {};
  argv.forEach(a => {
    const m = a.match(/^--([^=]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
    else if (a === '--defaults') out.defaults = true;
  });
  return out;
}

const DEFAULTS = { host: 'localhost', port: '3306', user: 'root', password: '', dbName: 'mavu_mill' };

// ── Entry point ─────────────────────────────────────────────
(async function main() {
  const args = parseArgs(process.argv.slice(2));

  console.log('');
  line();
  console.log('  Sakthi Mill — first time setup');
  line();

  const nonInteractive = args.defaults || args.host || args.user || args.db || args.password !== undefined;

  if (nonInteractive) {
    const cfg = {
      host: args.host || DEFAULTS.host,
      port: args.port || DEFAULTS.port,
      user: args.user || DEFAULTS.user,
      password: args.password !== undefined ? args.password : DEFAULTS.password,
      dbName: args.db || DEFAULTS.dbName
    };
    console.log(`\n  Using: ${cfg.user}@${cfg.host}:${cfg.port}, database "${cfg.dbName}"`);
    process.exit(await run(cfg));
  }

  // Interactive mode
  const readline = require('readline');
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = q => new Promise(r => rl.question(q, a => r(a.trim())));

  console.log('');
  console.log('  Press Enter to accept the [default] in brackets.');
  console.log('');

  if (fs.existsSync(ENV_PATH)) {
    const ow = await ask('  A .env already exists. Replace it? (y/n): ');
    if (ow.toLowerCase() !== 'y') {
      console.log('\n  Keeping your existing .env. Run "npm start" to launch.\n');
      rl.close();
      return;
    }
  }

  const cfg = {
    host: (await ask('  MySQL host [localhost]: ')) || DEFAULTS.host,
    port: (await ask('  MySQL port [3306]: ')) || DEFAULTS.port,
    user: (await ask('  MySQL username [root]: ')) || DEFAULTS.user,
    password: await ask('  MySQL password (Enter if none): '),
    dbName: (await ask('  Database name [mavu_mill]: ')) || DEFAULTS.dbName
  };
  rl.close();

  process.exit(await run(cfg));
})();
